sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "3.7"
install:
  - pip install git+https://github.com/acrisci/python-dbus-next.git@master#egg=dbus-next
  - pip install -r requirements.txt
script:
  - make style coverage
